# Generated by Django 5.0.6 on 2024-06-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('emprendedor', 'Emprendedor'), ('mentor', 'Mentor')], max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('user_name', models.CharField(max_length=30)),
                ('paternal_last_name', models.CharField(max_length=30)),
                ('maternal_last_name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('receive_updates', models.BooleanField(default=False)),
            ],
        ),
    ]
